apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
      - name: mq-container
        image: mq-image:latest
        ports:
        - containerPort: 1414
        - containerPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: mq-service
spec:
  selector:
    app: mq
  ports:
  - protocol: TCP
    port: 1414
    targetPort: 1414
  - protocol: TCP
    port: 9443
    targetPort: 9443

